<?php

use Drupal\Component\Serialization\Json;

/**
 * @file
 * Breakpoints JS.
 */

/**
 * Implements hook_page_attachments().
 */
function breakpointsjs_page_attachments(array &$attachments) {
  $theme_name = \Drupal::theme()->getActiveTheme()->getName();
  $attachments['#attached']['library'][] = 'breakpointsjs/breakpointsjs';
  $theme_breakpoints = \Drupal::service('breakpoint.manager')->getBreakpointsByGroup($theme_name);

  $settings = array();
  foreach ($theme_breakpoints as $breakpoint) {
    $settings[(string) $breakpoint->getLabel()]['name'] = (string) $breakpoint->getLabel();
    $settings[(string) $breakpoint->getLabel()]['media_query'] = $breakpoint->getMediaQuery();
    $settings[(string) $breakpoint->getLabel()]['multipliers'] = $breakpoint->getMultipliers();
  }

  $attachments['#attached']['drupalSettings']['breakpoints'] = $settings;
}

/**
 * Implements hook_libraries_info().
 *
 * @todo: Keep track of libraries api, it us currently totally broken.
 */
function breakpointsjs_libraries_info() {
  $libraries = array();

  $libraries['enquire'] = array(
    'name' => 'enquire.js',
    'vendor url' => 'http://wicky.nillia.ms/enquire.js/',
    'download url' => 'https://github.com/WickyNilliams/enquire.js/zipball/master',
    'version callback' => 'breakpointsjs_libraries_enquire_version',
    'files' => array(
      'js' => array(
        'dist/enquire.min.js' => array(
          'every_page' => TRUE,
        ),
      ),
    ),
  );

  return $libraries;
}

/**
 * Callback for enquire.js library version.
 *
 * @todo: Keep track of libraries api, it us currently totally broken.
 */
function breakpointsjs_libraries_enquire_version($library = array()) {
  $package_json = libraries_get_path('enquire') . '/package.json';

  if (!file_exists($package_json)) {
    return NULL;
  }

  $decoded_json = JSON::decode(file_get_contents($package_json, TRUE));

  return empty($decoded_json['version']) ? NULL : $decoded_json['version'];
}
